/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as ScenariosScenarioIdIndexRouteImport } from './routes/scenarios/$scenarioId/index'
import { Route as ScenariosScenarioIdDocsIndexRouteImport } from './routes/scenarios/$scenarioId/docs/index'
import { Route as ScenariosScenarioIdDocsNewIndexRouteImport } from './routes/scenarios/$scenarioId/docs/new/index'
import { Route as ScenariosScenarioIdDocsFilenameIndexRouteImport } from './routes/scenarios/$scenarioId/docs/$filename/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdIndexRoute =
  ScenariosScenarioIdIndexRouteImport.update({
    id: '/scenarios/$scenarioId/',
    path: '/scenarios/$scenarioId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosScenarioIdDocsIndexRoute =
  ScenariosScenarioIdDocsIndexRouteImport.update({
    id: '/scenarios/$scenarioId/docs/',
    path: '/scenarios/$scenarioId/docs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosScenarioIdDocsNewIndexRoute =
  ScenariosScenarioIdDocsNewIndexRouteImport.update({
    id: '/scenarios/$scenarioId/docs/new/',
    path: '/scenarios/$scenarioId/docs/new/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosScenarioIdDocsFilenameIndexRoute =
  ScenariosScenarioIdDocsFilenameIndexRouteImport.update({
    id: '/scenarios/$scenarioId/docs/$filename/',
    path: '/scenarios/$scenarioId/docs/$filename/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdIndexRoute
  '/scenarios/$scenarioId/docs': typeof ScenariosScenarioIdDocsIndexRoute
  '/scenarios/$scenarioId/docs/$filename': typeof ScenariosScenarioIdDocsFilenameIndexRoute
  '/scenarios/$scenarioId/docs/new': typeof ScenariosScenarioIdDocsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdIndexRoute
  '/scenarios/$scenarioId/docs': typeof ScenariosScenarioIdDocsIndexRoute
  '/scenarios/$scenarioId/docs/$filename': typeof ScenariosScenarioIdDocsFilenameIndexRoute
  '/scenarios/$scenarioId/docs/new': typeof ScenariosScenarioIdDocsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/scenarios/$scenarioId/': typeof ScenariosScenarioIdIndexRoute
  '/scenarios/$scenarioId/docs/': typeof ScenariosScenarioIdDocsIndexRoute
  '/scenarios/$scenarioId/docs/$filename/': typeof ScenariosScenarioIdDocsFilenameIndexRoute
  '/scenarios/$scenarioId/docs/new/': typeof ScenariosScenarioIdDocsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scenarios'
    | '/scenarios/$scenarioId'
    | '/scenarios/$scenarioId/docs'
    | '/scenarios/$scenarioId/docs/$filename'
    | '/scenarios/$scenarioId/docs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scenarios'
    | '/scenarios/$scenarioId'
    | '/scenarios/$scenarioId/docs'
    | '/scenarios/$scenarioId/docs/$filename'
    | '/scenarios/$scenarioId/docs/new'
  id:
    | '__root__'
    | '/'
    | '/scenarios/'
    | '/scenarios/$scenarioId/'
    | '/scenarios/$scenarioId/docs/'
    | '/scenarios/$scenarioId/docs/$filename/'
    | '/scenarios/$scenarioId/docs/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  ScenariosScenarioIdIndexRoute: typeof ScenariosScenarioIdIndexRoute
  ScenariosScenarioIdDocsIndexRoute: typeof ScenariosScenarioIdDocsIndexRoute
  ScenariosScenarioIdDocsFilenameIndexRoute: typeof ScenariosScenarioIdDocsFilenameIndexRoute
  ScenariosScenarioIdDocsNewIndexRoute: typeof ScenariosScenarioIdDocsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/': {
      id: '/scenarios/$scenarioId/'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ScenariosScenarioIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/docs/': {
      id: '/scenarios/$scenarioId/docs/'
      path: '/scenarios/$scenarioId/docs'
      fullPath: '/scenarios/$scenarioId/docs'
      preLoaderRoute: typeof ScenariosScenarioIdDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/docs/new/': {
      id: '/scenarios/$scenarioId/docs/new/'
      path: '/scenarios/$scenarioId/docs/new'
      fullPath: '/scenarios/$scenarioId/docs/new'
      preLoaderRoute: typeof ScenariosScenarioIdDocsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/docs/$filename/': {
      id: '/scenarios/$scenarioId/docs/$filename/'
      path: '/scenarios/$scenarioId/docs/$filename'
      fullPath: '/scenarios/$scenarioId/docs/$filename'
      preLoaderRoute: typeof ScenariosScenarioIdDocsFilenameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  ScenariosScenarioIdIndexRoute: ScenariosScenarioIdIndexRoute,
  ScenariosScenarioIdDocsIndexRoute: ScenariosScenarioIdDocsIndexRoute,
  ScenariosScenarioIdDocsFilenameIndexRoute:
    ScenariosScenarioIdDocsFilenameIndexRoute,
  ScenariosScenarioIdDocsNewIndexRoute: ScenariosScenarioIdDocsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
